name: Bug Report
description: Create a report to help us improve Transmute
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: How to reproduce?
      description: Steps to make the bug happen.
      placeholder: |
        1. Open App
        2. Drag file...
        3. Error appears
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: App Version
      placeholder: v1.0.0
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Windows
        - macOS
        - Linux
    validations:
      required: true
